### ISSUE TITLE
Error: Cannot find module 'meteor/tracker'

### ISSUE THREAD

**Issue by chip** [Astrocoders/compose-with-tracker#4]
Hi, Thanks for publishing this npm package. I'm getting the following error on my METEOR@1.4.4.1 project after installing this.

```
W20170424-17:57:32.778(-5)? (STDERR) Error: Cannot find module 'meteor/tracker'
W20170424-17:57:32.778(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20170424-17:57:32.779(-5)? (STDERR)     at Function.Module._load (module.js:276:25)
W20170424-17:57:32.779(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170424-17:57:32.779(-5)? (STDERR)     at require (internal/module.js:12:17)
W20170424-17:57:32.779(-5)? (STDERR)     at Object.<anonymous> (/Users/chip/code/invoicethat-reac
t/node_modules/compose-with-tracker/index.js:1:15)
W20170424-17:57:32.780(-5)? (STDERR)     at Module._compile (module.js:409:26)
W20170424-17:57:32.781(-5)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170424-17:57:32.781(-5)? (STDERR)     at Module.load (module.js:343:32)
W20170424-17:57:32.782(-5)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170424-17:57:32.782(-5)? (STDERR)     at Module.require (module.js:353:17)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by fakenickels** [comment]
Thanks for reporting the issue @chip
That's weird. Could you please create a reproduction repo for the issue?

**Comment by chip** [comment]
@grsabreu - Sorry I didn't do that earlier. I eventually got the code to work, but am getting this failure only in an enzyme test. I'm going to close this since I don't need the test anymore. Apologies for the noise. Thanks again.
